name: SAPYRO
favicon: null
layout_spectrum: 0.2902771681547165
typography_spectrum: 0.5862369458191097
title: 'FOREST FIRES BARRIES, PORTABLE AND REUSABLE'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7601896135602146
  lightness: 0.16363523504696786
  saturation: 0.27766039106063545
  rhythmicContrast: 0.05515513150021434
purpose: []
