name: SAPYRO
favicon: null
layout_spectrum: 0.24854
typography_spectrum: 0.59319
title: SAPYRO
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#008935'
    - '#ffe000'
    - '#de0000'
    - '#161616'
    - '#fe6300'
  brandStrength: 0.875
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
